# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 16:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.RemoveField(
            model_name='character',
            name='ruby_number',
        ),
        migrations.AddField(
            model_name='parameters',
            name='agility',
            field=models.PositiveIntegerField(default=1, help_text="Character's agility", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Agility'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='defense',
            field=models.PositiveIntegerField(default=1, help_text="Character's defense", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Defense'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='durability',
            field=models.PositiveIntegerField(default=1, help_text="Character's durability", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durability'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='luck',
            field=models.PositiveIntegerField(default=1, help_text="Character's Luck", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Luck'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='strength',
            field=models.PositiveIntegerField(default=1, help_text="Character's stregnth", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Strength'),
        ),
        migrations.AlterField(
            model_name='character',
            name='health',
            field=models.PositiveSmallIntegerField(default=100, help_text="Actual character'health value", validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Health'),
        ),
    ]
