# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20180313_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='at_work',
            field=models.BooleanField(default=False, help_text='Is character on work flag', verbose_name='At work flag'),
        ),
        migrations.AddField(
            model_name='character',
            name='mission_start_time',
            field=models.DateTimeField(blank=True, help_text='Mission start time', null=True, verbose_name='Mission start time'),
        ),
        migrations.AddField(
            model_name='character',
            name='on_mission',
            field=models.BooleanField(default=False, help_text='Is character on mission flag', verbose_name='On Mission flag'),
        ),
        migrations.AddField(
            model_name='character',
            name='work_start_time',
            field=models.DateTimeField(blank=True, help_text='Work start time', null=True, verbose_name='Work start time'),
        ),
    ]
