# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20180313_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='at_work',
        ),
        migrations.RemoveField(
            model_name='character',
            name='on_mission',
        ),
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('BUSY', 'Busy'), ('MISSION', 'Mission'), ('WORK', 'Work'), ('REST', 'Rest')], default='FREE', help_text='Is character at work, on mission etc?', max_length=10, verbose_name='Character status'),
        ),
    ]
