# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 18:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20180314_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0, help_text='Character gold', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gold'),
        ),
    ]
