# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0004_auto_20180314_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1, help_text='Mission type', max_length=20, verbose_name='Mission type')),
                ('reward', models.IntegerField(blank=True, help_text='Reward for work', null=True, verbose_name='Reward')),
                ('started', models.DateTimeField(blank=True, help_text='Started time', null=True, verbose_name='Started time')),
                ('character', models.ForeignKey(help_text='Mission belongs to character', on_delete=django.db.models.deletion.CASCADE, to='character.Character', verbose_name='Character mission')),
            ],
        ),
    ]
