# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='started',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Started time', verbose_name='Started time'),
        ),
    ]
