# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20180318_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.IntegerField(choices=[(1, '1 hours'), (2, '2 hours'), (3, '3 hours'), (4, '4 hours'), (5, '5 hours'), (6, '6 hours'), (7, '7 hours'), (8, '8 hours'), (9, '9 hours'), (10, '10 hours'), (11, '11 hours'), (12, '12 hours'), (13, '13 hours'), (14, '14 hours'), (15, '15 hours'), (16, '16 hours'), (17, '17 hours'), (18, '18 hours'), (19, '19 hours'), (20, '20 hours'), (21, '21 hours'), (22, '22 hours'), (23, '23 hours'), (24, '24 hours')], default=1, help_text='Mission type', max_length=20, verbose_name='Mission type'),
        ),
    ]
