# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='character',
            field=models.OneToOneField(default=1, help_text='Character assgined to this profile', on_delete=django.db.models.deletion.CASCADE, to='character.Character', verbose_name='Character'),
            preserve_default=False,
        ),
    ]
