# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180301_2010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Premium',
        ),
    ]
