# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Your account image', null=True, upload_to='user_profiles', verbose_name='Image'),
        ),
    ]
